spring.application.name=praticaum
spring.datasource.url=jbdc:postegresql://localhost:5432/praticaum
spring.datasource.username=postgres
spring.datasource.password=ALUNO 
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postegresql.Driver
